apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: insurance-rag
spec:
  selector:
    app: app
  ports:
    - name: api
      port: 8000
      targetPort: 8000
    - name: streamlit
      port: 8501
      targetPort: 8501
  type: ClusterIP
